<a href="https://colab.research.google.com/github/suhailamohammed/8-Puzzle-Problem/blob/main/8_Puzzle_with_A_star_search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1910496**

**Suhaila**

In [5]:
import numpy as np
from collections import deque

In [6]:
def goalMatch(mat):
  for i in range(n):
    for j in range(n):
      if (mat[i][j] != final[i][j]):
        return False
        
  return True  


In [7]:
def findCoordinates(mat):
  for i in range(n):
    for j in range(n):
      if (mat[i][j] == -1):
        #print(i,j)
        return i,j
  
    

In [8]:
def generateChildren(mat,final,x,y):
  mydict = {}
  
  #for left shift
  if y != 0:
    c = mat.copy()
    temp = c[x][y]
    c[x][y] = c[x][y-1]
    c[x][y-1] = temp
    
    h = heuristicCalc(c,final)
    mydict[h,'left'] = c
    
  
  #for right shift
  if y != n-1 :
    c1 = mat.copy()
    temp = c1[x][y]
    c1[x][y] = c1[x][y+1]
    c1[x][y+1] = temp
    h = heuristicCalc(c1,final)
    mydict[h,'right'] = c1
    

  #for top shift
  if x != 0:
    c1 = mat.copy()
    temp = c1[x][y]
    c1[x][y] = c1[x-1][y]
    c1[x-1][y] = temp
    h = heuristicCalc(c1,final)
    mydict[h,'Up'] = c1
    

  #for bottom shift
  if x != n-1:
    c1 = mat.copy()
    temp = c1[x][y]
    c1[x][y] = c1[x+1][y]
    c1[x+1][y] = temp
    h = heuristicCalc(c1,final)
    mydict[h,'down'] = c1

 
  return mydict


In [9]:
def DFBB(mat, x,y,final,cost,bound):
  
  children = {}

  children = generateChildren(mat,final,x,y)


  h_least = (float('inf'),'')

  #Finds the state with the least cost
  for key in children:

    if key[0] < h_least[0]:
      h_least = key
  
  path.append(h_least[1])
  
  if cost + h_least[0]  < bound:
    stack.append(children[h_least])
    if goalMatch(children[h_least]):
      bound = cost
    else:
      cost = cost + 1
      x1,y1 = findCoordinates(children[h_least])
      DFBB(children[h_least],x1,y1,final,cost,bound)
  
  return path,stack


In [10]:
# Function to calculate the number of
# misplaced tiles ie. number of non-blank
# tiles not in their goal position
def heuristicCalc(mat, final) -> int:
	
	count = 0
	for i in range(n):
		for j in range(n):
			if (mat[i][j] != final[i][j]):
				count += 1
				
	return count

In [11]:
# Driver Code
#Test1
initial = np.array([ [ 1, 4, 2 ],
			[ -1, 5, 3],
			[ 6, 7, 8 ] ])


final = np.array([ [ 1, 2, -1 ],
			[ 5, 4, 3],
			[ 6, 7, 8 ] ])


# Position of the blank tile 
x = 1 
y = 0


bound = np.inf

#size of the puzzle
n = 3
stack = deque()

path = ['start']


# Function call to solve the puzzle
moves,solution= DFBB(initial, x,y, final,0,bound)

#Print the actions
print("moves=",moves)

#Print the movement of the tile
for i in range(len(solution)-1):
	print(solution[i])
	print('-->')
print(solution[i+1])


moves= ['start', 'right', 'Up', 'right']
[[ 1  4  2]
 [ 5 -1  3]
 [ 6  7  8]]
-->
[[ 1 -1  2]
 [ 5  4  3]
 [ 6  7  8]]
-->
[[ 1  2 -1]
 [ 5  4  3]
 [ 6  7  8]]


In [12]:
#Test2

initial = np.array([ [ 1, 4, 2 ],
			[ -1, 5, 3],
			[ 6, 7, 8 ] ])



final = np.array([ [ 1, 2, 3 ],
			[ 5, 4, 8],
			[ 6, 7, -1 ] ])

# Position of the blank tile 
x = 1 
y = 0


bound = np.inf

#size of the puzzle
n = 3
stack = deque()

path = ['start']



# Function call to solve the puzzle
moves,solution= DFBB(initial, x,y, final,0,bound)

#Print the actions
print("moves=",moves)

#Print the movement of the tile
for i in range(len(solution)-1):
	print(solution[i])
	print('-->')
print(solution[i+1])



moves= ['start', 'right', 'Up', 'right', 'down', 'down']
[[ 1  4  2]
 [ 5 -1  3]
 [ 6  7  8]]
-->
[[ 1 -1  2]
 [ 5  4  3]
 [ 6  7  8]]
-->
[[ 1  2 -1]
 [ 5  4  3]
 [ 6  7  8]]
-->
[[ 1  2  3]
 [ 5  4 -1]
 [ 6  7  8]]
-->
[[ 1  2  3]
 [ 5  4  8]
 [ 6  7 -1]]


In [13]:
#Test3

initial = np.array([ [ 1, 2, 3 ],
			[ -1, 5, 4],
			[ 6, 7, 8 ] ])


final = np.array([ [ 1, 2, 3 ],
			[ 5, 4, 8],
			[ 6, 7, -1 ] ])

# Position of the blank tile 
x = 1 
y = 0


bound = np.inf

#size of the puzzle
n = 3
stack = deque()

path = ['start']

# Function call to solve the puzzle
moves,solution= DFBB(initial, x,y, final,0,bound)

#Print the actions
print("moves=",moves)

#Print the movement of the tile
for i in range(len(solution)-1):
	print(solution[i])
	print('-->')
print(solution[i+1])



moves= ['start', 'right', 'right', 'down']
[[ 1  2  3]
 [ 5 -1  4]
 [ 6  7  8]]
-->
[[ 1  2  3]
 [ 5  4 -1]
 [ 6  7  8]]
-->
[[ 1  2  3]
 [ 5  4  8]
 [ 6  7 -1]]
