<a href="https://colab.research.google.com/github/suhailamohammed/8-Puzzle-Problem/blob/main/AI_Assignment3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def goalMatch(mat):
  for i in range(n):
    for j in range(n):
      if (mat[i][j] != final[i][j]):
        return False
        
  return True  


In [ ]:
def findCoordinates(mat):
  l = list()
  for i in range(n):
    for j in range(n):
      if (mat[i][j] == 0):
        #print(i,j)
        return i,j
  
    

In [ ]:
def store(visit):
  visitList.append(visit)

In [ ]:
def checkvisit(mat):
  
  for ele in visitList:
    count = 0
    for i in range(n):
      for j in range(n):
        if(ele[i][j] == mat[i][j]):
            count = count + 1
    if count == 9:
      return True  
  return False

In [ ]:
def deleteVisited(mat, key):
  del mat[key]
  return mat

In [ ]:
def DFBB(mat, x,y,final,cost):
  
  childs = {}
  bound = float('inf')
  print('Selected matrix=' , mat)

  childs = generateChildren(mat,final,x,y)

  '''
  for key in childs:
    if checkvisit(childs[key]):
      childs = deleteVisited(childs, key)
   
'''

  print("-------------------All options------------------------")
  print( childs)
  print('----------------------END-----------------------------')
  
  help = (float('inf'),'')

  for key in childs:

    if key[0] < help[0]:
      help = key

  path.append(help[1])
  
  if cost + help[0]  < bound:
    if goalMatch(childs[help]):
      bound = cost
    else:
      cost = cost + 1
      x1,y1 = findCoordinates(childs[help])
      store(childs[help])
      print(x1,y1)
      DFBB(childs[help],x1,y1,final,cost)
  
  return path


In [ ]:
'''
def printmatrix(mat):
  for i in range(n):
	  for j in range(n):
		  print("%d " % (mat[i][j]), end = " ")
			
	  print()
'''

'\ndef printmatrix(mat):\n  for i in range(n):\n\t  for j in range(n):\n\t\t  print("%d " % (mat[i][j]), end = " ")\n\t\t\t\n\t  print()\n'

In [ ]:
# Function to calculate the number of
# misplaced tiles ie. number of non-blank
# tiles not in their goal position
def heuristicCalc(mat, final) -> int:
	
	count = 0
	for i in range(n):
		for j in range(n):
			if (mat[i][j] != final[i][j]):
				count += 1
				
	return count

In [ ]:
def generateChildren(mat,final,x,y):
  mydict = {}
  
  #for left shift
  if y != 0:
    c = mat.copy()
    temp = c[x][y]
    c[x][y] = c[x][y-1]
    c[x][y-1] = temp
    
    h = heuristicCalc(c,final)
    mydict[h,'left'] = c
    
  
  #for right shift
  if y != n-1 :
    c1 = mat.copy()
    temp = c1[x][y]
    c1[x][y] = c1[x][y+1]
    c1[x][y+1] = temp
    h = heuristicCalc(c1,final)
    mydict[h,'right'] = c1
    

  #for top shift
  if x != 0:
    c1 = mat.copy()
    temp = c1[x][y]
    c1[x][y] = c1[x-1][y]
    c1[x-1][y] = temp
    h = heuristicCalc(c1,final)
    mydict[h,'Up'] = c1
    

  #for bottom shift
  if x != n-1:
    c1 = mat.copy()
    temp = c1[x][y]
    c1[x][y] = c1[x+1][y]
    c1[x+1][y] = temp
    h = heuristicCalc(c1,final)
    mydict[h,'down'] = c1

 
  return mydict


In [ ]:
def getInvCount(arr):
    inv_count = 0
    empty_value = -1
    for i in range(0, 9):
        for j in range(i + 1, 9):
            if arr[j] != empty_value and arr[i] != empty_value and arr[i] > arr[j]:
                inv_count += 1
    return inv_count
 
     
# This function returns true
# if given 8 puzzle is solvable.
def isSolvable(puzzle) :
 
    # Count inversions in given 8 puzzle
    inv_count = getInvCount([j for sub in puzzle for j in sub])
 
    # return true if inversion count is even.
    return (inv_count % 2 == 0)



In [ ]:
# Driver Code

# Initial configuration
# Value 0 is used for empty space
initial = np.array([ [ 1, 4, 2 ],
			[ 0, 5, 3],
			[ 6, 7, 8 ] ])

# Solvable Final configuration
# Value 0 is used for empty space
final = np.array([ [ 1, 2, 0 ],
			[ 5, 4, 3],
			[ 6, 7, 8 ] ])

# Blank tile coordinates in
# initial configuration
x = 1 
y = 0

n = 3
path = ['start']
visitList = list()
if(isSolvable(initial)):
	print("Solvable")
	#generateChildren(initial,final,x,y)
	# Function call to solve the puzzle
	print(DFBB(initial, x,y, final,0))
 
else:
  print("Not Solvable")



#printmatrix(initial)


Solvable
Selected matrix= [[1 4 2]
 [0 5 3]
 [6 7 8]]
-------------------All options------------------------
{(3, 'right'): array([[1, 4, 2],
       [5, 0, 3],
       [6, 7, 8]]), (5, 'Up'): array([[0, 4, 2],
       [1, 5, 3],
       [6, 7, 8]]), (5, 'down'): array([[1, 4, 2],
       [6, 5, 3],
       [0, 7, 8]])}
----------------------END-----------------------------
1 1
Selected matrix= [[1 4 2]
 [5 0 3]
 [6 7 8]]
-------------------All options------------------------
{(4, 'left'): array([[1, 4, 2],
       [0, 5, 3],
       [6, 7, 8]]), (4, 'right'): array([[1, 4, 2],
       [5, 3, 0],
       [6, 7, 8]]), (2, 'Up'): array([[1, 0, 2],
       [5, 4, 3],
       [6, 7, 8]]), (4, 'down'): array([[1, 4, 2],
       [5, 7, 3],
       [6, 0, 8]])}
----------------------END-----------------------------
0 1
Selected matrix= [[1 0 2]
 [5 4 3]
 [6 7 8]]
-------------------All options------------------------
{(3, 'left'): array([[0, 1, 2],
       [5, 4, 3],
       [6, 7, 8]]), (0, 'right'): array(